### ISSUE TITLE
Version 1.4.0 darkmode is subjectively uglier than in 1.3.0

### ISSUE THREAD

**Issue by ejmin** [teal77/trireme#73] opened 2023-12-29 12:14 UTC
I get this may be a matter of opinion, but consider these two screens. 
Subjectively, the colors are too bright, lots of space is wasted on some components...

Old version, 1.3.0
![photo_2023-12-29_13-10-51](https://github.com/teal77/trireme/assets/86563329/74cc8166-a38a-46ac-90ee-1c40b96b60fd)

New version 1.4.0
![photo_2023-12-29_13-10-53](https://github.com/teal77/trireme/assets/86563329/f01117a4-7123-4a17-97f8-05aca635dee8)

**Comment by teal77** [comment] 2023-12-29 13:59
Should be fixed in 1.4.1

Issue in F-Droid build because F-Droid built the app with a newer Flutter
version than was intended. (Caused by Flutter sdk version constraint no
longer failing the build on version mismatch)

**Comment by ejmin** [comment] 2024-01-02 11:46
Good fix in F-droid version 1.4.1

**Closed as completed** 2024-01-02 11:46 UTC
